### ISSUE TITLE
Listado de todos los proyectos 

### ISSUE THREAD

**Issue by Topi99** [eacp/daw-webyte-caritas-codigo#3]
Crear view de el listado de los protectos en HandleBars.

La información va a llegar con el siguiente formato de contexto:
```
{
  proyectos:
    [{},{},{}]
}
```

Y se llama la información con la siguiente sintaxis:

```
{{#each proyectos}}

{{/each}}
```

**Comment by eacp** [comment]
Yo la creo ahorita si quieren en el route /

**Comment by eacp** [comment]
Ya esta

**Comment by eacp** [comment]
Mejorar vista
